name: imgDigest
services:
  img-digest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imgDigest
    command: sleep infinity
    ports:
        - 80:8080
    volumes:
        - ./src/public:/usr/local/bin/public
        - ../..:/workspaces:cached
volumes:
  ./src/public