services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imgDigest
    image: img-digest
    command: /usr/local/bin/app
    ports:
        - 80:8080
    volumes:
        - .:/usr/src/app
