name: compose
services:
  img-digest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imgDigest
    command: sleep infinity
    ports:
      - 8080:8080
    volumes:
      - ./src/public:/usr/local/bin/public
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined